update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -109,9 +109,31 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: Deploy App to Dokploy
-        uses: qbix-tech/dokploy-deploy-action@v1
-        with:
-          dokploy_url: https://dokploy.k2dv.io
-          api_key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
-          application_id: UtH-sYqz1xNb43i7BnEiJ
+      - name: Deploy Application
+        shell: bash
+        env:
+          DOKPLOY_URL: ${{secrets.DOKPLOY_HOST}}
+          DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
+          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_APPLICATION_ID }}
+        run: |
+          response=$(curl -X 'POST' \
+            "$DOKPLOY_URL/api/application.deploy" \
+            -H 'Accept: application/json' \
+            -H 'Content-Type: application/json' \
+            -H "X-API-Key: $DOKPLOY_API_KEY" \
+            -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
+            -w "%{http_code}" \
+            -o /dev/null \
+            -s)
+
+          if [ "$response" -ne 200 ]; then
+            echo "Deployment failed with status code: $response"
+            exit 1
+          fi
+
+      # - name: Deploy App to Dokploy
+      #   uses: qbix-tech/dokploy-deploy-action@v1
+      #   with:
+      #     dokploy_url: https://dokploy.k2dv.io
+      #     api_key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
+      #     application_id: UtH-sYqz1xNb43i7BnEiJ
